[package]
edition = "2021"
name = "chess"
version = "0.1.0"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
serde = {version = "1.0.202", features = ["derive"]}
serde_derive = "1.0"
shakmaty = "0.27.0"
thiserror = "1.0.61"
tracing = "0.1.40"
